# Generated by Django 3.2.13 on 2024-10-31 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('appointment_type', models.CharField(choices=[('1', 'Stock Investment'), ('2', 'Real Estate'), ('4', 'Personal Finance'), ('more than 3', 'Others')], default='1', max_length=15)),
                ('appointment_date_time', models.DateTimeField()),
                ('message', models.CharField(max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('created',),
            },
        ),
    ]
